### ISSUE TITLE
Youtube images aren't loading when deployed to Vercel

### ISSUE THREAD

**Issue by jamesnw** [11ty/api-opengraph-image#6]
Example-
https://www.zachleat.com/web/youtube-embeds/

or direct link-
https://v1.opengraph.11ty.dev/https%3A%2F%2Fyoutube.com%2Fwatch%3Fv%3DYYJpFdEaAuc/auto/jpeg/

It appears that Youtube is serving content without the expected `meta[property='og:image']` tag when fetched from Vercel's servers. I am able to run the `vercel-1` branch successfully locally, but when I deploy to Vercel, that tag is not present in Youtube's response. I changed the script to return the fetched HTML if no images are found, and verified that tag is missing from Youtube's response. 

I don't know that there is a fix on our end for this communication issue between Vercel and Youtube, but wanted to at least document the issue..

**Comment by zachleat** [comment]
Pushed a fix for this one, more info at #7.

Shipping live now.

**Comment by zachleat** [comment]
Pushed some more improvements to this for YouTube urls this morning.
